### ISSUE TITLE
folders don't work

### ISSUE THREAD

**Issue by Inetov** [tabeyti/jenkins-jack#56]
Hi! this is the story in two screenshots:
![settings](https://user-images.githubusercontent.com/45286374/111673925-84a0c780-882c-11eb-923c-d6798d8a9ecd.jpg)
![the_problem](https://user-images.githubusercontent.com/45286374/111673930-85395e00-882c-11eb-9f0f-0d91d5376a50.jpg)

I specified folderFilter in the config, but Jenkins Jack ignores this and creates a job in the root folder. If I move the job manually and run it again, Jenkins Jack will say that this job doesn't exist and offer to create it.

Directory Jack_tests exists in root.
Jenkins version: 2.263.4
Jenkins Jack version: 1.1.2

**Comment by tabeyti** [comment]
Hey @Inetov!

Executing a pipeline script in a folder, although supported, isn't very straightforward, or user friendly at this time. Here are the instructions for executing a local script on a pipeline within a folder on the Jenkins server:

https://github.com/tabeyti/jenkins-jack/blob/master/CHANGELOG.md#pipeline-jack

Because this is a pain in the ass and not intuitive whatsoever, I'm making this a feature: have a list of Jenkins folders on the server display to the user on job creation so they can select one to create their job under.

In fact, I already have a change for this and will (hopefully) be rolling it out in 1.1.13 within the next day or so.

**Comment by Inetov** [comment]
Hey @tabeyti!
it's cool, but I don't understand what I did wrong in my example.
I hope the new version will solve my problem)

**Comment by Inetov** [comment]
Hey @tabeyti!
Currently I have version 1.1.5 and folder selector in interface works great! thank you!
